apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
spec:
  selector: frontend-deployment
#  template: ...
  volumeMounts:
  - mountPath: /opt/
    name: test-cm
volumes:
   - name: test-cm
     configMap:
        name: test-cm
