apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  volumeMounts:
  - mountPath: /opt/
    name: test-cm
volumes:
   - name: test-cm
     configMap:
        name: test-cm
