apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      serviceAccountName: default
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: test-cm
          resources:
            cpu: "100m"
            memory: "128mi"
          limits:
            cpu:  "100m"
            memory: "128mi"

