apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      serviceAccountName: default
      containers:
      - name: app
        image: nginx:1.22.1

        envFrom:
        - configMapRef:
            name: test-cm
              #        env:
              #        - name: AWS_SECRET_ACCESS_KEY
              #          value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"

