apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base/
namespace: dev
patchesStrategicMerge:
 - hpa.yaml

images:
 - name: alpine
   newName: mobinesh/alpine
   newTag: v1.1.0
