apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base/
namespace: dev
# patchesStrategicMerge:
#  - hpa.yaml

images:
 - name: localhost:5000/ubuntu
   newTag: v.1.1
