apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./nodeport.yaml
namespace: dev
patchesStrategicMerge:
- deployment.yaml
images:
- name: nginx 
  newTag: 1.22.2
configMapGenerator:
- name: test-cm
  envs:
  - env
  - env2
