apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base/
namespace: dev
patchesStrategicMerge:
 - hpa.yaml

images:
 - name: nginx
   newName: nginx
   newTag: 1.22.1
