apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
patchesStrategicMerge:
- deployment.yaml
images:
- name: nginx 
  newTag: 1.22.1
configMapGenerator:
- name: test-cm
  envs:
  - env
  - env2
