apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base/
namespace: dev
# patchesStrategicMerge:
#  - hpa.yaml

images:
 - name: mobinesh/alpine
   newTag: v1.22.4
secretGenerator:
  - name: test-sec
    files:
      - secret
  #  namespace: dev
 configMapGenerator: 
   - name: test-cm
     files:
       - configmap
       
