apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
patchesStrategicMerge:
- deployment.yaml
images:
- name: mobinesh/alpine
  newTag: v1.22.4
configMapGenerator:
- name: test-cm
  files:
    - configmap
    - developers
