apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base/
namespace: dev
# patchesStrategicMerge:
#  - hpa.yaml

images:
 - name: harbor.tasn.ir/library/alpine
   newTag: "3.11"
