apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-tls-reader-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: vault-access
  namespace: dev
roleRef:
  kind: Role
  name: vault-tls-reader
  apiGroup: rbac.authorization.k8s.io
