apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  namespace: prod
patchesStrategicMerge:
  - rollout-replica.yaml
  - hpa.yaml
  - service-nodeport.yaml 
