apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: prod
patchesStrategicMerge:
  - hpa.yaml
  - service-nodeport.yaml 
resources:
  - rollout-replica.yaml

images:
 - name: alpine
   newName: mobinesh/alpine
   newTag: 1.0.1
