apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        vault.security.banzaicloud.io/vault-agent: "false"
    spec:
      serviceAccountName: default
      containers:
        - name: app
          image: mobinesh/nginx:1.22.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 512mi
            limits:
              cpu: 200m
              memory: 512mi
      restartpolicy: OnFailure
          env:
            - name: AWS_SECRET_ACCESS_ID
              value: vault:secret/data/accounts/aws#AWS_ACCESS_KEY_ID
            - name: FARANEGAR_API_KEY
              value: vault:secret/data/accounts/FARANEGAR_API_KEY_SEC#FARANEGAR_API_KEY
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

