apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
    #  annotations:
    #    vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
    #    vault.security.banzaicloud.io/vault-ignore-missing-secrets: "true"
    #    vault.security.banzaicloud.io/vault-tls-secret: "skip"  # Update this line
    #    vault.security.banzaicloud.io/vault-skip-verify: "false"
    #    vault.security.banzaicloud.io/vault-role: "default"
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: app
        image: mobinesh/alpine
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
